image: docker
services:
  - docker:dind
variables:
  DOCKER_TLS_CERTDIR: ""
stages:
  - stage
deploy-stage:
  stage: stage
  only:
    - stage
  script:
    - docker kill nvstr-front
    - docker rm nvstr-front
    - docker build -t nvstr --build-arg APP_ENV="$APP_ENV" . --no-cache
    - docker run -d -p 4444:4444 --restart always --name nvstr-front nvstr
  tags:
    - build_docker
