image: docker
services:
  - docker:dind
variables:
  DOCKER_TLS_CERTDIR: ""
stages:
  - stage
deploy-stage:
  stage: stage
  only:
    - stage
  script:
    - docker build -t nvstr --build-arg APP_ENV="$VARIABLE_NAME" . --no-cache
    - docker run -d -p 4444:4444 --rm --name nvstr-front-${CI_JOB_ID} nvstr
  tags:
    - build_docker
