image: docker
services:
  - docker:dind
variables:
  DOCKER_TLS_CERTDIR: ""
stages:
  - stage
deploy-stage:
  stage: stage
  only:
    - stage
  script:
    - docker build -t nvstr .
    - docker run -it -p 4444:4444 nvstr
  tags:
    - build_docker
